# Generated by Django 2.2 on 2022-10-23 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricanteSmartPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais_origen', models.CharField(max_length=255)),
                ('fecha_fundacion', models.DateField(default=datetime.date.today)),
                ('link_pagina_web', models.URLField(default=None)),
            ],
        ),
    ]
