# Generated by Django 2.2 on 2022-10-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('almacenamiento', models.IntegerField()),
                ('tamaño_pantalla', models.CharField(max_length=255)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_manager.FabricanteSmartPhones')),
            ],
        ),
    ]
