# Generated by Django 2.2.20 on 2022-11-05 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
